pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main',
                url: 'https://github.com/vishwash-debug/php-k8s-devops-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t php-app .'
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker stop php-container || true'
                sh 'docker rm php-container || true'
            }
        }

        stage('Run New Container') {
            steps {
                sh 'docker run -d -p 80:80 --name php-container php-app'
            }
        }

    }
}
